config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("src.cashflows.urls")),
    # third party urls
    path("__debug__/", include("debug_toolbar.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

src/cashflows/urls.py
from django.urls import path
from .views import home, create_cashflow_view, delete_cashflow_view

urlpatterns = [
    path("", home, name="home"),
    path("create", create_cashflow_view, name="create_cashflow"),
    path("<int:id>/delete", delete_cashflow_view, name="delete_cashflow"),
]

src/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

src/cashflows/models.py
from django.db import models
from django.core.validators import MinValueValidator

from .querysets import CashflowQuerySet


# Create your models here.
class Cashflow(models.Model):
    TYPE_CHOICES = [
        ("income", "Income"),
        ("need", "Need"),
        ("want", "Want"),
        ("saving", "Saving"),
    ]

    SOURCE_CHOICES = [
        ("salary", "Salary"),
        ("bonus", "Bonus"),
        ("regular_bill", "Regular Bill"),
        ("irregular_bill", "Irregular Bill"),
        ("savings", "Savings"),
    ]

    type = models.CharField(
        max_length=10,
        choices=TYPE_CHOICES,
    )
    source = models.CharField(
        max_length=20,
        choices=SOURCE_CHOICES,
    )
    name = models.CharField(
        max_length=30,
    )
    amount = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        validators=[MinValueValidator(0)],
    )

    objects = CashflowQuerySet.as_manager()

    def __str__(self) -> str:
        return f"{self.name}"

src/cashflows/forms.py
from django import forms
from .models import Cashflow


class CashflowForm(forms.ModelForm):
    class Meta:
        model = Cashflow
        fields = [
            "type",
            "source",
            "name",
            "amount",
        ]

src/cashflows/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import CashflowForm
from .models import Cashflow


# Create your views here.
def home(request: HttpRequest):
    form = CashflowForm()
    cashflows = Cashflow.objects.all().order_by("-amount")
    cashflow_percentages = cashflows.expense_percentages()  # type: ignore

    context = {
        "form": form,
        "cashflows": cashflows,
        "cashflow_percentages": cashflow_percentages,
    }

    return render(
        request,
        "cashflows/home.html",
        context,
    )


def create_cashflow_view(request: HttpRequest):
    form = CashflowForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
    return redirect(reverse("home"))


def delete_cashflow_view(request: HttpRequest, id):
    if request.method == "POST":
        Cashflow.objects.get(id=id).delete()
    return redirect(reverse("home"))

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/daisyui@3.3.1/dist/full.css" rel="stylesheet" type="text/css" />
  <script src="https://cdn.tailwindcss.com"></script>

  <title>
    {% if title %}
      {{ title }}
    {% else %}
      SavingSync
    {% endif %}
  </title>

</head>
<body class="container mx-auto max-w-4xl px-2">
 {% block main %}
   
 {% endblock main %}
</body>
</html>

src/templates/cashflows/delete_cashflow_form.html
<form action="{% url 'delete_cashflow' item.id %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline btn-error">Delete</button>
</form>

src/templates/cashflows/home.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block main %}

<!-- High-level stats -->
{% if cashflows %}
  <div class="grid grid-cols-2 gap-4  my-8">
    <ul>
      <li data-testid="monthly-balance">Monthly Balance: £{{ cashflows.monthly_balance|floatformat:2  }}</li>
      <li data-testid="biannual-balance">Biannual Balance: £{{ cashflows.biannual_balance|floatformat:2  }}</li>
      <li data-testid="annual-balance">Annual Balance: £{{ cashflows.annual_balance|floatformat:2  }}</li>
    </ul>
    <ul data-testid="expense-percentages">
      <li>Needs: {{ cashflow_percentages.needs|floatformat:0  }}%</li>
      <li>Wants: {{ cashflow_percentages.wants|floatformat:0  }}%</li>
      <li>Savings: {{ cashflow_percentages.savings|floatformat:0  }}%</li>
    </ul>
  </div>
{% endif %}


<div class="md:flex">
  <!-- Create Cashflow form -->
  <div class="container w-full my-8 md:my-0 md:mr-10">
    <form action="{% url 'create_cashflow' %}" method="POST" class="my-6 md:my-0">
      {% csrf_token %}
  
      <div class="grid grid-cols-2 gap-4 mb-4">
        <div class="form-control w-full">
          <label for="id_source">Type</label>
          {% render_field form.type class+="select select-bordered w-full max-w-xs" %}
        </div>
        <div class="form-control w-full">
          <label for="id_source">Source</label>
          {% render_field form.source class+="select select-bordered w-full max-w-xs" %}
        </div>
        <div class="form-control w-full">
          <label for="id_name">Name</label>
          {% render_field form.name class+="input input-bordered w-full max-w-xs" %}
        </div>
        <div class="form-control w-full">
          <label for="id_amount">Amount</label>
          {% render_field form.amount class+="input input-bordered w-full max-w-xs" %}
        </div>
      </div>
      <div>
        <button type="submit" class="btn btn-outline btn-primary w-full md:w-1/5">
          Add
        </button>
      </div>
    </form>
  </div>
  
  <!-- Cashflows table -->
  <div class="container text-center">
    {% if cashflows %}
  
      <div class="overflow-x-auto h-96">
        <table id="income-list" class="table table-pin-rows">
          <!-- head -->
          <thead>
            <tr>
              <th>Incomes</th>
              <th class="max-md:hidden">Source</th>
              <th class="max-md:hidden">Name</th>
              <th>Amount (£)</th>
              <th>Action</th>
            </tr>
          </thead>
  
          <!-- Incomes -->
          <tbody>
            {% for item in cashflows.incomes %}
              {% include "cashflows/list-item.html" with testid="income-list-item" %}
            {% endfor %}
          </tbody>
  
          <!-- Expenses -->
          <thead>
            <tr>
              <th>Expenses</th>
            </tr>
          </thead>
          <tbody>
            {% for item in cashflows.expenses %}
              {% include "cashflows/list-item.html" with testid="expense-list-item" %}
            {% endfor %}
          </tbody>
        </table>
      </div>
  
    {% else %}
      <p>No items yet</p>
    {% endif %}
  </div>
</div>
  

{% endblock main %}

src/templates/cashflows/list-item.html
<tr data-testid="{{ testid }}" class="hover">
  <th class="max-md:hidden">{{ item.get_type_display }}</th>
  <th class="max-md:hidden">{{ item.get_source_display}}</th>
  <td>{{ item.name }}</td>
  <td>{{ item.amount }}</td>
  <td>{% include 'cashflows/delete_cashflow_form.html' %}</td>
</tr>

src/templates/home.html
{% extends "base.html" %}

{% block main %}
  
{% if cashflows %}
  <h2 data-testid="monthly-balance">Monthly Balance: £{{ cashflows.monthly_balance|floatformat:2  }}</h2>
  <h2 data-testid="biannual-balance">Biannual Balance: £{{ cashflows.biannual_balance|floatformat:2  }}</h2>
  <h2 data-testid="annual-balance">Annual Balance: £{{ cashflows.annual_balance|floatformat:2  }}</h2>
{% endif %}

<form action="{% url 'create_cashflow' %}" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Add</button>
</form>

{% if cashflows %}

  <div class="overflow-x-auto h-96">
    <table id="income-list" class="table table-pin-rows">
      <!-- head -->
      <thead>
        <tr>
          <th>Incomes</th>
          <th>Source</th>
          <th>Name</th>
          <th>Amount (£)</th>
          <th>Action</th>
        </tr>
      </thead>

      <!-- Incomes -->
      <tbody>
        {% for item in cashflows.incomes %}
          <tr data-testid="income-list-item" class="hover">
            <th></th>
            <th>{{ item.get_source_display}}</th>
            <td>{{ item.name }}</td>
            <td>{{ item.amount }}</td>
            <td>{% include 'delete_cashflow_form.html' %}</td>
          </tr>
          {% endfor %}
      </tbody>

      <!-- Expenses -->
      <thead>
        <tr>
          <th>Expenses</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cashflows.expenses %}
          <tr data-testid="expense-list-item" class="hover">
            <th></th>
            <th>{{ item.get_source_display}}</th>
            <td>{{ item.name }}</td>
            <td>{{ item.amount }}</td>
            <td>{% include 'delete_cashflow_form.html' %}</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
    

{% else %}
  <p>No items yet</p>
{% endif %}
  

{% endblock main %}